name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sabianrobi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            sabianrobi/frameshelf-backend:latest
            sabianrobi/frameshelf-backend:${{ steps.get_version.outputs.version }}
